/**
 * Contact discovery and the verification cascade.
 *
 * Nothing here invents a person and nothing here invents an address. Contacts
 * come from evidence already in the database — a job description that names a
 * recruiter, an address embedded in a Who's-Hiring post, a mailto on a team
 * page, a LinkedIn row, or something the operator typed. Addresses are either
 * observed the same way, or generated by applying a pattern that was itself
 * inferred from observed addresses at that domain, and then confirmed by a
 * verifier before anyone would email them.
 *
 * The cascade, cheapest first:
 *   free DNS/syntax/role prefilter → domain pattern conformance → paid verifier
 * and every step writes a field_observation carrying the evidence FK it came
 * from, so any value in the UI can be traced back to the document that produced
 * it.
 */

import { gunzipSync } from 'node:zlib';
import type { Company, Confidence, Contact, Persona, SourceId, VerificationVerdict } from '../../shared/types.js';
import type { ContactRow } from '../../shared/ipc.js';
import { scoreContact } from '../../shared/score.js';
import { electPrimaryContact } from './scoring.js';
import { resolveEntityField } from './ingest.js';
import { COMPANY_SUPPRESSION_MATCH } from './suppression.js';
import { type Db, all, get, prep, run, ulid } from '../db/index.js';
import {
  domainOf,
  getCatchAllFlag,
  isRoleAccount,
  localPartOf,
  normalizeEmail,
  verdictReliability,
} from '../verify/mx.js';
import {
  generateCandidates,
  globalPatternOrder,
  loadPattern,
  patternConformance,
  refreshPattern,
  splitFullName,
  type EmailPattern,
} from '../verify/pattern.js';
import {
  loadVerifierConfig,
  verifyEmails,
  type VerifierConfig,
  type VerifyResult,
} from '../verify/verifier.js';

// ─────────────────────────────────────────────────────────────────────────────
// Persona classification — a rule table, deliberately not an LLM
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Personas drive who gets emailed first, so this has to be auditable: when the
 * operator asks why a VP Eng was ranked above the Head of Talent, the answer
 * must be a line of this table, not a sampled token. It is also free and runs
 * in microseconds over thousands of rows.
 *
 * Order matters. The first match wins, so specific titles are listed before the
 * generic seniority fallback.
 */
const PERSONA_RULES: { persona: Persona; re: RegExp }[] = [
  {
    persona: 'founder_ceo',
    re: /\b(co[-\s]?founder|founder|founding (partner|team)|c\.?e\.?o\.?|chief executive|managing director|owner|proprietor)\b/i,
  },
  {
    persona: 'cto_vpe',
    re: /\b(c\.?t\.?o\.?|chief technolog\w*|chief technical|chief architect|v\.?p\.?\s*(of\s*)?(engineering|eng|technology|r&d)|vice president[,\s]+(of\s+)?(engineering|technology)|svp\s*(of\s*)?engineering|head of (engineering|technology|platform|infrastructure)|director of engineering|engineering director|vp eng)\b/i,
  },
  {
    persona: 'head_of_talent',
    re: /\b(head of (talent|people|recruiting|recruitment|hr|human resources)|chief people|chief talent|c\.?h\.?r\.?o\.?|v\.?p\.?\s*(of\s*)?(talent|people|hr|human resources)|vice president[,\s]+(of\s+)?(talent|people)|director of (talent|people|recruiting|recruitment|hr|human resources)|talent director|people director|head of talent acquisition)\b/i,
  },
  {
    persona: 'recruiter',
    re: /\b(recruiter|recruiting (manager|lead|partner|coordinator|specialist)|technical recruiting|talent acquisition|talent partner|talent manager|talent lead|sourcer|sourcing (lead|specialist|manager)|people ops|people operations|hr (manager|generalist|business partner|coordinator)|hrbp|staffing)\b/i,
  },
  {
    persona: 'coo_ops',
    re: /\b(c\.?o\.?o\.?|chief operating|chief of staff|c\.?f\.?o\.?|chief financial|v\.?p\.?\s*(of\s*)?(operations|ops|finance)|head of (operations|ops|finance|business operations)|director of operations|business operations|controller|office manager)\b/i,
  },
  {
    persona: 'hiring_manager',
    re: /\b(head of|director|senior director|v\.?p\.?|vice president|manager|team lead|tech lead|lead engineer|principal|staff engineer|chief \w+ officer|c\.?p\.?o\.?|c\.?m\.?o\.?|c\.?r\.?o\.?)\b/i,
  },
];

export function classifyPersona(title: string | null | undefined): Persona | null {
  if (!title) return null;
  const t = title.replace(/\s+/g, ' ').trim();
  if (!t) return null;
  for (const { persona, re } of PERSONA_RULES) {
    if (re.test(t)) return persona;
  }
  return 'other';
}

const SENIORITY_RULES: { level: string; re: RegExp }[] = [
  { level: 'founder', re: /\b(co[-\s]?founder|founder)\b/i },
  { level: 'c_level', re: /\b(c\.?[a-z]\.?o\.?|chief\s+\w+)\b/i },
  { level: 'vp', re: /\b(v\.?p\.?|vice president|svp|evp)\b/i },
  { level: 'director', re: /\b(director|head of)\b/i },
  { level: 'manager', re: /\b(manager|lead)\b/i },
  { level: 'ic', re: /\b(engineer|designer|analyst|specialist|coordinator|associate|recruiter|sourcer)\b/i },
];

export function classifySeniority(title: string | null | undefined): string | null {
  if (!title) return null;
  for (const { level, re } of SENIORITY_RULES) if (re.test(title)) return level;
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Provenance
// ─────────────────────────────────────────────────────────────────────────────

export interface ObservationInput {
  entity: 'company' | 'contact' | 'req';
  entityId: string;
  field: string;
  value: string | null;
  source: SourceId;
  evidenceId: number | null;
  confidence: Confidence;
}

/**
 * Append the observation, then recompute the winner for that field. Resolving
 * at write time is what lets the UI read a field with one b-tree seek instead
 * of a window function over the whole history.
 */
export function recordObservation(db: Db, o: ObservationInput): number {
  const inserted = prep(
    db,
    `INSERT INTO field_observation (entity, entity_id, field, value, source, evidence_id, confidence)
     VALUES (?, ?, ?, ?, ?, ?, ?)
     RETURNING id`,
  ).get(o.entity, o.entityId, o.field, o.value, o.source, o.evidenceId, o.confidence) as { id: number };

  // ONE resolver for the whole app — ingest.ts's, which ranks by source trust
  // (an inference can never beat something actually observed) and computes
  // conflict over the latest observation per source. This module used to run
  // its own confidence-ranked variant with all-history conflicts; whichever
  // wrote last won, and the provenance panel depended on write order.
  resolveEntityField(db, o.entity, o.entityId, o.field);
  return inserted.id;
}

// ─────────────────────────────────────────────────────────────────────────────
// Row loading / mapping
// ─────────────────────────────────────────────────────────────────────────────

interface CompanyDbRow {
  id: string;
  domain: string | null;
  name: string;
  name_norm: string;
  headcount: number | null;
  industry: string | null;
  hq_location: string | null;
  in_bay_area: number;
  funding_stage: string | null;
  last_round_at: number | null;
  yc_batch: string | null;
  ats_platform: string | null;
  ats_token: string | null;
  careers_url: string | null;
  linkedin_url: string | null;
  website: string | null;
  open_req_count: number;
  open_req_eng_count: number;
  max_days_open: number | null;
  stale_req_count: number;
  recruiter_count: number | null;
  has_inhouse_ta: number | null;
  no_agency_policy: number;
  quality_score: number | null;
  score_breakdown: string | null;
  status: string;
  reviewed: number;
  reviewed_at: number | null;
  notes: string | null;
  created_at: number;
  updated_at: number;
}

interface ContactDbRow {
  id: string;
  company_id: string;
  first_name: string | null;
  last_name: string | null;
  full_name: string;
  title: string | null;
  persona: string | null;
  seniority: string | null;
  email: string | null;
  email_source: string | null;
  email_verdict: VerificationVerdict;
  email_verified_at: number | null;
  email_pattern: string | null;
  phone: string | null;
  linkedin_url: string | null;
  is_primary: number;
  contact_score: number | null;
  status: string;
  reviewed: number;
  notes: string | null;
  created_at: number;
  updated_at: number;
}

export function loadCompany(db: Db, companyId: string): Company | null {
  const r = get<CompanyDbRow>(db, 'SELECT * FROM company WHERE id = ?', companyId);
  if (!r) return null;
  return {
    id: r.id,
    domain: r.domain,
    name: r.name,
    nameNorm: r.name_norm,
    headcount: r.headcount,
    headcountSource: null,
    industry: r.industry,
    hqLocation: r.hq_location,
    inBayArea: r.in_bay_area === 1,
    fundingStage: r.funding_stage,
    lastRoundAt: r.last_round_at == null ? null : new Date(r.last_round_at).toISOString(),
    atsPlatform: (r.ats_platform as Company['atsPlatform']) ?? null,
    atsToken: r.ats_token,
    careersUrl: r.careers_url,
    linkedinUrl: r.linkedin_url,
    ycBatch: r.yc_batch,
    openReqCount: r.open_req_count,
    openReqEngCount: r.open_req_eng_count,
    maxDaysOpen: r.max_days_open,
    staleReqCount: r.stale_req_count,
    recruiterCount: r.recruiter_count,
    hasInhouseTa: r.has_inhouse_ta == null ? null : r.has_inhouse_ta === 1,
    noAgencyPolicy: r.no_agency_policy === 1,
    qualityScore: r.quality_score,
    scoreBreakdown: r.score_breakdown,
    status: r.status as Company['status'],
    reviewed: r.reviewed === 1,
    reviewedAt: r.reviewed_at == null ? null : new Date(r.reviewed_at).toISOString(),
    notes: r.notes,
    createdAt: new Date(r.created_at).toISOString(),
    updatedAt: new Date(r.updated_at).toISOString(),
  };
}

function toContact(r: ContactDbRow): Contact {
  return {
    id: r.id,
    companyId: r.company_id,
    firstName: r.first_name,
    lastName: r.last_name,
    fullName: r.full_name,
    title: r.title,
    persona: (r.persona as Persona) ?? null,
    seniority: r.seniority,
    email: r.email,
    emailSource: (r.email_source as SourceId) ?? null,
    emailVerdict: r.email_verdict,
    emailVerifiedAt: r.email_verified_at == null ? null : new Date(r.email_verified_at).toISOString(),
    phone: r.phone,
    linkedinUrl: r.linkedin_url,
    isPrimary: r.is_primary === 1,
    contactScore: r.contact_score,
    status: r.status as Contact['status'],
    reviewed: r.reviewed === 1,
    notes: r.notes,
    createdAt: new Date(r.created_at).toISOString(),
    updatedAt: new Date(r.updated_at).toISOString(),
  };
}

export function toContactRow(r: ContactDbRow): ContactRow {
  return {
    id: r.id,
    companyId: r.company_id,
    fullName: r.full_name,
    firstName: r.first_name,
    lastName: r.last_name,
    title: r.title,
    persona: (r.persona as Persona) ?? null,
    email: r.email,
    emailVerdict: r.email_verdict,
    emailVerifiedAt: r.email_verified_at,
    emailSource: r.email_source,
    phone: r.phone,
    linkedinUrl: r.linkedin_url,
    isPrimary: r.is_primary === 1,
    contactScore: r.contact_score,
    status: r.status,
    reviewed: r.reviewed === 1,
    notes: r.notes,
  };
}

function contactRows(db: Db, companyId: string): ContactDbRow[] {
  return all<ContactDbRow>(
    db,
    'SELECT * FROM contact WHERE company_id = ? ORDER BY contact_score DESC NULLS LAST, created_at ASC',
    companyId,
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Evidence mining
// ─────────────────────────────────────────────────────────────────────────────

const EMAIL_IN_TEXT = /[A-Za-z0-9!#$%&'*+/=?^_`{|}~.-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+/g;

/** Decompressed raw_response bodies, cached for the duration of a run. */
const bodyCache = new Map<number, string>();
const BODY_CACHE_LIMIT = 64;

function bodyOf(row: { id: number; body: Uint8Array | null; encoding: string }): string {
  if (!row.body) return '';
  const hit = bodyCache.get(row.id);
  if (hit !== undefined) return hit;
  let text = '';
  try {
    text =
      row.encoding === 'gzip'
        ? gunzipSync(Buffer.from(row.body)).toString('utf8')
        : Buffer.from(row.body).toString('utf8');
  } catch {
    text = '';
  }
  if (bodyCache.size >= BODY_CACHE_LIMIT) {
    const oldest = bodyCache.keys().next().value;
    if (oldest !== undefined) bodyCache.delete(oldest);
  }
  bodyCache.set(row.id, text);
  return text;
}

function belongsToDomain(email: string, domain: string): boolean {
  const d = domainOf(email);
  return d === domain || d.endsWith(`.${domain}`);
}

/** Title-case a local part only when it clearly encodes two name tokens. */
function nameFromLocalPart(local: string): { first: string; last: string } | null {
  const m = local.toLowerCase().match(/^([a-z]{2,})[._-]([a-z]{2,})$/);
  if (!m) return null;
  const cap = (s: string) => s[0]!.toUpperCase() + s.slice(1);
  return { first: cap(m[1]!), last: cap(m[2]!) };
}

/**
 * A person's name written near an address in prose. Deliberately narrow: two or
 * three capitalised words immediately before the address or its mailto link.
 * A wrong guess here is worse than no guess, so anything ambiguous is dropped.
 */
const NEARBY_NAME = /([A-Z][a-z]{1,20}(?:\s+[A-Z][a-z]{1,20}){1,2})\s*(?:[-–—,:(<]|\s+at\s+|\s*$)/g;

function personNearEmail(text: string, index: number): { name: string; title: string | null } | null {
  const window = text.slice(Math.max(0, index - 160), index);
  const cleaned = window.replace(/<[^>]*>/g, ' ').replace(/&[a-z]+;/gi, ' ').replace(/\s+/g, ' ');

  // The NEAREST preceding name, not the first one in the window — a team page
  // lists many people and the first match would attach everyone's address to
  // whoever appears at the top.
  NEARBY_NAME.lastIndex = 0;
  let candidate: string | null = null;
  let end = -1;
  for (const m of cleaned.matchAll(NEARBY_NAME)) {
    const stop = (m.index ?? 0) + m[1]!.length;
    if (stop > end) {
      end = stop;
      candidate = m[1]!.trim();
    }
  }
  if (!candidate) return null;

  const tail = cleaned.slice(end);
  // Another address between the name and this one means this address belongs to
  // somebody else (or to nobody, as with a trailing jobs@ link).
  if (tail.includes('@')) return null;
  if (tail.replace(/[^A-Za-z]/g, '').length > 24) return null;

  // Reject obvious non-people picked up from page furniture.
  if (/\b(Contact|Email|Careers|Jobs|Apply|Team|About|Privacy|Terms|Send|Reach|Open Roles)\b/.test(candidate)) {
    return null;
  }

  // The text between the name and the address is usually the title. It is only
  // kept when the persona rule table recognises it, which is a much stronger
  // filter than any length or punctuation heuristic.
  const raw = tail
    .replace(/^[\s\-–—,:|·•()]+/, '')
    .replace(/["'<>|].*$/, '')
    .replace(/[\s,:;.\-–—]+$/, '')
    .trim();
  const persona = raw.length >= 2 && raw.length <= 60 ? classifyPersona(raw) : null;
  return { name: candidate, title: persona && persona !== 'other' ? raw : null };
}

interface HarvestedEmail {
  email: string;
  fullName: string | null;
  title: string | null;
  source: SourceId;
  evidenceId: number | null;
  confidence: Confidence;
}

function harvestFromDocuments(db: Db, company: Company): HarvestedEmail[] {
  const domain = company.domain;
  if (!domain) return [];
  const out: HarvestedEmail[] = [];
  const seen = new Set<string>();

  const push = (h: HarvestedEmail) => {
    if (seen.has(h.email)) return;
    seen.add(h.email);
    out.push(h);
  };

  // Careers / team pages fetched for this company.
  const pages = all<{ id: number; source: string; url: string | null; body: Uint8Array | null; encoding: string }>(
    db,
    `SELECT id, source, url, body, encoding
       FROM raw_response
      WHERE source IN ('careers_page','yc','sec_formd')
        AND url IS NOT NULL
        AND lower(url) LIKE ?
      ORDER BY fetched_at DESC
      LIMIT 40`,
    `%${domain.toLowerCase()}%`,
  );

  // Who's-Hiring threads are one document covering many companies, so they are
  // scanned wholesale and filtered by address domain.
  const hn = all<{ id: number; source: string; url: string | null; body: Uint8Array | null; encoding: string }>(
    db,
    `SELECT id, source, url, body, encoding
       FROM raw_response
      WHERE source = 'hn_whoishiring'
      ORDER BY fetched_at DESC
      LIMIT 24`,
  );

  for (const row of [...pages, ...hn]) {
    const text = bodyOf(row);
    if (!text) continue;
    EMAIL_IN_TEXT.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = EMAIL_IN_TEXT.exec(text)) !== null) {
      const email = normalizeEmail(m[0]!);
      if (!email || !belongsToDomain(email, domain)) continue;
      const nearby = personNearEmail(text, m.index);
      const derived = nameFromLocalPart(localPartOf(email));
      const fullName = nearby?.name ?? (derived ? `${derived.first} ${derived.last}` : null);
      push({
        email,
        fullName,
        title: nearby?.title ?? null,
        source: row.source as SourceId,
        evidenceId: row.id,
        // The address is observed, so it is solid; the name attached to it is
        // inferred from surrounding text, which is why this is not 'high'.
        confidence: nearby ? 'medium' : 'low',
      });
    }
  }

  return out;
}

/**
 * "Jane Doe", "Jane Doe <jane@acme.com>", "Jane Doe, Head of Talent",
 * "reach out to jane@acme.com" — the shapes an LLM classifier actually writes
 * into req.named_contact, plus bare addresses found in a job description.
 */
export function parseNamedContact(raw: string): { fullName: string | null; email: string | null; title: string | null } {
  const text = raw.trim();
  if (!text) return { fullName: null, email: null, title: null };

  let email: string | null = null;
  EMAIL_IN_TEXT.lastIndex = 0;
  const em = EMAIL_IN_TEXT.exec(text);
  if (em) email = normalizeEmail(em[0]!);

  const withoutEmail = text.replace(EMAIL_IN_TEXT, ' ').replace(/[<>()]/g, ' ').replace(/\s+/g, ' ').trim();
  const parts = withoutEmail.split(/\s*[,—–|]\s*|\s+-\s+/).map((p) => p.trim()).filter(Boolean);

  let fullName: string | null = null;
  let title: string | null = null;
  for (const part of parts) {
    const looksLikeName = /^[A-Z][a-z'’-]+(\s+[A-Z][a-z'’.-]+){1,2}$/.test(part);
    if (!fullName && looksLikeName) fullName = part;
    else if (!title && part.length >= 3 && /[a-z]/.test(part)) title = part;
  }
  if (!fullName && parts.length === 1 && /^[A-Z][a-z'’-]+$/.test(parts[0]!)) fullName = parts[0]!;

  return { fullName, email, title };
}

// ─────────────────────────────────────────────────────────────────────────────
// Contact upsert
// ─────────────────────────────────────────────────────────────────────────────

export interface ContactInput {
  fullName: string;
  firstName?: string | null;
  lastName?: string | null;
  title?: string | null;
  email?: string | null;
  emailSource?: SourceId | null;
  emailPattern?: EmailPattern | null;
  phone?: string | null;
  linkedinUrl?: string | null;
  source: SourceId;
  evidenceId?: number | null;
  confidence?: Confidence;
}

function normKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z]/g, '');
}

/**
 * Insert or merge. Matching is by address first (globally unique in the
 * schema), then by normalised name within the company, so re-running discovery
 * enriches the same row rather than fanning out duplicates.
 */
export function upsertContact(db: Db, companyId: string, input: ContactInput): ContactDbRow | null {
  const fullName = input.fullName.replace(/\s+/g, ' ').trim();
  if (!fullName) return null;

  const split = splitFullName(fullName);
  const firstName = input.firstName ?? (split.first || null);
  const lastName = input.lastName ?? (split.last || null);
  const email = input.email ? normalizeEmail(input.email) : null;
  const confidence = input.confidence ?? 'medium';

  let existing: ContactDbRow | undefined;
  if (email) {
    existing = get<ContactDbRow>(db, 'SELECT * FROM contact WHERE email = ?', email);
    // The unique index on email is global. An address already claimed by another
    // company is a data conflict, not something to overwrite silently.
    if (existing && existing.company_id !== companyId) return null;
  }
  if (!existing) {
    const byName = all<ContactDbRow>(db, 'SELECT * FROM contact WHERE company_id = ?', companyId).find(
      (c) => normKey(c.full_name) === normKey(fullName),
    );
    existing = byName;
  }

  const title = input.title ?? existing?.title ?? null;
  const persona = classifyPersona(title) ?? (existing?.persona as Persona | null) ?? null;
  const seniority = classifySeniority(title) ?? existing?.seniority ?? null;

  let id: string;
  if (existing) {
    id = existing.id;

    // An address already on the row is never silently replaced — both values
    // stay in field_observation and the conflict surfaces in the UI. The one
    // exception is upgrading a shared mailbox to a named person's address.
    let finalEmail = existing.email;
    if (email && (!finalEmail || (isRoleAccount(finalEmail) && !isRoleAccount(email)))) finalEmail = email;
    const emailChanged = finalEmail !== existing.email;

    run(
      db,
      `UPDATE contact SET
         first_name   = coalesce(?, first_name),
         last_name    = coalesce(?, last_name),
         full_name    = ?,
         title        = coalesce(?, title),
         persona      = coalesce(?, persona),
         seniority    = coalesce(?, seniority),
         email        = ?,
         email_source = CASE WHEN ? = 1 THEN ? ELSE email_source END,
         email_verdict = CASE WHEN ? = 1 THEN 'unverified' ELSE email_verdict END,
         email_verified_at = CASE WHEN ? = 1 THEN NULL ELSE email_verified_at END,
         email_pattern = CASE WHEN ? = 1 THEN ? ELSE email_pattern END,
         phone        = coalesce(?, phone),
         linkedin_url = coalesce(?, linkedin_url),
         updated_at   = unixepoch('subsec')*1000
       WHERE id = ?`,
      firstName,
      lastName,
      existing.full_name.length >= fullName.length ? existing.full_name : fullName,
      title,
      persona,
      seniority,
      finalEmail,
      emailChanged ? 1 : 0,
      input.emailSource ?? input.source,
      emailChanged ? 1 : 0,
      emailChanged ? 1 : 0,
      emailChanged ? 1 : 0,
      input.emailPattern ?? null,
      input.phone ?? null,
      input.linkedinUrl ?? null,
      id,
    );
  } else {
    id = ulid();
    run(
      db,
      `INSERT INTO contact (id, company_id, first_name, last_name, full_name, title, persona, seniority,
                            email, email_source, email_pattern, phone, linkedin_url)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      id,
      companyId,
      firstName,
      lastName,
      fullName,
      title,
      persona,
      seniority,
      email,
      email ? (input.emailSource ?? input.source) : null,
      input.emailPattern ?? null,
      input.phone ?? null,
      input.linkedinUrl ?? null,
    );
  }

  const ev = input.evidenceId ?? null;
  recordObservation(db, { entity: 'contact', entityId: id, field: 'full_name', value: fullName, source: input.source, evidenceId: ev, confidence });
  if (title) {
    recordObservation(db, { entity: 'contact', entityId: id, field: 'title', value: title, source: input.source, evidenceId: ev, confidence });
  }
  if (email) {
    recordObservation(db, {
      entity: 'contact',
      entityId: id,
      field: 'email',
      value: email,
      source: input.emailSource ?? input.source,
      evidenceId: ev,
      confidence,
    });
  }
  if (input.linkedinUrl) {
    recordObservation(db, { entity: 'contact', entityId: id, field: 'linkedin_url', value: input.linkedinUrl, source: input.source, evidenceId: ev, confidence });
  }

  return get<ContactDbRow>(db, 'SELECT * FROM contact WHERE id = ?', id)!;
}

// ─────────────────────────────────────────────────────────────────────────────
// Discovery
// ─────────────────────────────────────────────────────────────────────────────

export interface DiscoverOptions {
  /** Also propose pattern-generated addresses for named people with none. */
  generateCandidates?: boolean;
  /** Candidates per person when the domain's pattern is known / unknown. */
  candidatesWithPattern?: number;
  candidatesWithoutPattern?: number;
}

export interface DiscoveryReport {
  companyId: string;
  contacts: ContactRow[];
  created: number;
  updated: number;
  observedEmails: number;
  /** Addresses proposed from the domain pattern, not yet verified. */
  proposed: { contactId: string; email: string; pattern: EmailPattern; rank: number }[];
  notes: string[];
}

/**
 * Assemble every contact this company's existing evidence supports. Free — it
 * touches no network beyond DNS and spends nothing.
 */
export async function discoverContacts(
  db: Db,
  companyId: string,
  opts: DiscoverOptions = {},
): Promise<DiscoveryReport> {
  const company = loadCompany(db, companyId);
  if (!company) throw new Error(`Unknown company: ${companyId}`);

  const before = new Set(contactRows(db, companyId).map((c) => c.id));
  const notes: string[] = [];
  let observedEmails = 0;

  // ① Job descriptions that name a person.
  // req.source is NOT NULL and only ever written with SourceId members.
  const reqs = all<{ id: number; named_contact: string | null; description: string | null; url: string; source: SourceId }>(
    db,
    `SELECT id, named_contact, description, url, source FROM req WHERE company_id = ? AND closed_at IS NULL`,
    companyId,
  );

  for (const req of reqs) {
    if (req.named_contact) {
      const parsed = parseNamedContact(req.named_contact);
      if (parsed.fullName) {
        upsertContact(db, companyId, {
          fullName: parsed.fullName,
          title: parsed.title,
          email: parsed.email,
          // Provenance carries the req's ACTUAL source — a lever or ashby
          // harvest labelled 'greenhouse' poisons the provenance panel.
          source: req.source,
          confidence: 'high',
        });
        if (parsed.email) observedEmails++;
      }
    }

    // Addresses written into the description itself.
    if (req.description && company.domain) {
      EMAIL_IN_TEXT.lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = EMAIL_IN_TEXT.exec(req.description)) !== null) {
        const email = normalizeEmail(m[0]!);
        if (!email || !belongsToDomain(email, company.domain)) continue;
        const nearby = personNearEmail(req.description, m.index);
        const derived = nameFromLocalPart(localPartOf(email));
        const fullName = nearby?.name ?? (derived ? `${derived.first} ${derived.last}` : null);
        if (!fullName) continue;
        upsertContact(db, companyId, {
          fullName,
          email,
          title: nearby?.title ?? null,
          source: 'careers_page',
          confidence: 'medium',
        });
        observedEmails++;
      }
    }
  }

  // ② Careers/team pages and Who's-Hiring posts.
  for (const h of harvestFromDocuments(db, company)) {
    if (!h.fullName) {
      // An address with no attributable person. Role mailboxes are still worth
      // keeping as a last-resort contact; anonymous personal addresses are not.
      if (!isRoleAccount(h.email)) continue;
      upsertContact(db, companyId, {
        fullName: `${company.name} (${localPartOf(h.email)})`,
        email: h.email,
        title: null,
        source: h.source,
        evidenceId: h.evidenceId,
        confidence: h.confidence,
      });
      observedEmails++;
      continue;
    }
    upsertContact(db, companyId, {
      fullName: h.fullName,
      email: h.email,
      title: h.title,
      source: h.source,
      evidenceId: h.evidenceId,
      confidence: h.confidence,
    });
    observedEmails++;
  }

  // ③ Company-level observations that carry an address (LinkedIn and others).
  const companyEmailObs = all<{ value: string | null; source: string; evidence_id: number | null }>(
    db,
    `SELECT value, source, evidence_id
       FROM field_observation
      WHERE entity = 'company' AND entity_id = ? AND field LIKE '%email%' AND value IS NOT NULL`,
    companyId,
  );
  for (const o of companyEmailObs) {
    const email = normalizeEmail(o.value);
    if (!email || !company.domain || !belongsToDomain(email, company.domain)) continue;
    const derived = nameFromLocalPart(localPartOf(email));
    const fullName = derived
      ? `${derived.first} ${derived.last}`
      : isRoleAccount(email)
        ? `${company.name} (${localPartOf(email)})`
        : null;
    if (!fullName) continue;
    upsertContact(db, companyId, {
      fullName,
      email,
      source: o.source as SourceId,
      evidenceId: o.evidence_id,
      confidence: 'medium',
    });
    observedEmails++;
  }

  // ④ Pattern-generated candidates for named people with no address yet.
  const proposed: DiscoveryReport['proposed'] = [];
  if (opts.generateCandidates !== false && company.domain) {
    const stored = loadPattern(db, company.domain);
    const inferred = stored?.pattern
      ? stored
      : refreshPattern(db, company.domain).pattern
        ? loadPattern(db, company.domain)
        : null;
    const order = globalPatternOrder(db);
    const limit = inferred?.pattern
      ? (opts.candidatesWithPattern ?? 1)
      : (opts.candidatesWithoutPattern ?? 2);

    for (const c of contactRows(db, companyId)) {
      if (c.email) continue;
      if (!c.first_name) continue;
      const candidates = generateCandidates(c.first_name, c.last_name, company.domain, inferred?.pattern ?? null, {
        limit,
        confidence: inferred?.confidence ?? 0,
        order,
      });
      for (const cand of candidates) {
        proposed.push({ contactId: c.id, email: cand.email, pattern: cand.pattern, rank: cand.rank });
      }
    }
    if (inferred?.pattern) {
      notes.push(
        `Domain pattern ${inferred.pattern} (confidence ${inferred.confidence.toFixed(2)} from ${inferred.sampleCount} observed address${inferred.sampleCount === 1 ? '' : 'es'}).`,
      );
    } else if (proposed.length) {
      notes.push('No confirmed pattern for this domain — candidates are ranked guesses awaiting verification.');
    }
  }

  const after = contactRows(db, companyId);
  const created = after.filter((c) => !before.has(c.id)).length;

  return {
    companyId,
    contacts: after.map(toContactRow),
    created,
    updated: after.length - created,
    observedEmails,
    proposed,
    notes,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// The decision table
// ─────────────────────────────────────────────────────────────────────────────

export type ContactDecision = 'send' | 'review' | 'reject';

export interface DecisionInput {
  verdict: VerificationVerdict;
  catchAll: boolean | null;
  /** 0-1, from pattern.patternConformance(). */
  patternConformance: number;
  /** Distinct non-inferred sources that observed this address. 0 = pure guess. */
  sourceCount: number;
  role?: boolean;
  /** mx.verdictReliability() for the address's mail provider. */
  mxReliability?: 'high' | 'medium' | 'low';
}

export interface Decision {
  decision: ContactDecision;
  reason: string;
}

/**
 * Catch-all domains are always REVIEW, never an automatic send: on a catch-all
 * the server accepts every address, so a "valid" verdict carries no information
 * and sending is a coin flip against the bounce rate that protects the
 * operator's personal Gmail. The operator's instruction is to exclude them
 * unless there is no alternative, which is a judgement only they can make —
 * hence review rather than reject.
 */
export function decideContact(i: DecisionInput): Decision {
  if (i.verdict === 'disposable') return { decision: 'reject', reason: 'Disposable mailbox' };
  if (i.verdict === 'invalid') return { decision: 'reject', reason: 'Address does not exist' };

  if (i.role || i.verdict === 'role') {
    if (i.verdict === 'valid') {
      return { decision: 'review', reason: 'Role mailbox, confirmed to exist — not a named person' };
    }
    return { decision: 'reject', reason: 'Role mailbox with no positive confirmation it exists' };
  }

  if (i.catchAll === true || i.verdict === 'catch_all') {
    return { decision: 'review', reason: 'Catch-all domain — acceptance proves nothing' };
  }

  if (i.verdict === 'valid') {
    // mx.ts verdictReliability: Microsoft 365 and SEG gateways accept nearly
    // everything at RCPT, so a paid "valid" carries little information there —
    // the documented policy routes those to review instead of send.
    if (i.mxReliability === 'low') {
      return { decision: 'review', reason: 'Verifier says valid, but this mail provider accepts almost anything — review' };
    }
    if (i.sourceCount > 0) return { decision: 'send', reason: 'Observed address, verified deliverable' };
    if (i.patternConformance >= 0.6) {
      return { decision: 'send', reason: 'Pattern-derived address, verified deliverable' };
    }
    return { decision: 'review', reason: 'Verified deliverable but derived from a weak pattern' };
  }

  if (i.verdict === 'unknown') {
    if (i.sourceCount > 0) return { decision: 'review', reason: 'Observed address, verifier inconclusive' };
    if (i.patternConformance >= 0.6) {
      return { decision: 'review', reason: 'Strong pattern match, verifier inconclusive' };
    }
    return { decision: 'reject', reason: 'Unconfirmed guess with a weak pattern match' };
  }

  // 'unverified'
  if (i.sourceCount > 0) return { decision: 'review', reason: 'Observed address, not yet verified' };
  return { decision: 'reject', reason: 'Unverified guess' };
}

// ─────────────────────────────────────────────────────────────────────────────
// Verification cascade
// ─────────────────────────────────────────────────────────────────────────────

export interface VerifyCompanyOptions {
  force?: boolean;
  /** Also try pattern-generated addresses for people with none. */
  tryCandidates?: boolean;
  candidatesWithPattern?: number;
  candidatesWithoutPattern?: number;
  config?: VerifierConfig;
  /**
   * Restrict the run to one contact. The operator's `v` key re-verifies one
   * person — without this, force-re-verifying one contact re-charged every
   * address at the company.
   */
  onlyContactId?: string;
}

export interface VerifyCompanyReport {
  companyId: string;
  contacts: ContactRow[];
  verified: number;
  costMicros: number;
  decisions: { contactId: string; email: string | null; decision: ContactDecision; reason: string }[];
  blocked: boolean;
  notes: string[];
}

function isSuppressed(db: Db, company: Company): string | null {
  if (company.domain) {
    const d = get<{ reason: string }>(
      db,
      "SELECT reason FROM suppression WHERE kind = 'domain' AND lower(value) = ?",
      company.domain.toLowerCase(),
    );
    if (d) return `domain suppressed (${d.reason})`;
  }
  // The same triple-identity match every other barrier uses — a raw
  // `value = company.id` compare never matched (values are stored lowercased,
  // ULIDs are uppercase) and paid verifier credits were spent on suppressed
  // companies.
  const c = get<{ reason: string }>(
    db,
    `SELECT s.reason FROM suppression s
      WHERE s.kind = 'company'
        AND EXISTS (SELECT 1 FROM company co WHERE co.id = ? AND ${COMPANY_SUPPRESSION_MATCH})
      LIMIT 1`,
    company.id,
  );
  return c ? `company suppressed (${c.reason})` : null;
}

function emailSuppressed(db: Db, email: string): boolean {
  return Boolean(
    get<{ id: number }>(db, "SELECT id FROM suppression WHERE kind = 'email' AND lower(value) = ?", email),
  );
}

function sourceCountFor(db: Db, contactId: string, email: string): number {
  return (
    get<{ n: number }>(
      db,
      `SELECT count(DISTINCT source) AS n
         FROM field_observation
        WHERE entity = 'contact' AND entity_id = ? AND field = 'email'
          AND lower(value) = ? AND source <> 'pattern_inference'`,
      contactId,
      email,
    )?.n ?? 0
  );
}

function applyVerdict(
  db: Db,
  contact: ContactDbRow,
  email: string,
  result: VerifyResult,
  pattern: EmailPattern | null,
): void {
  // contact.email carries a global UNIQUE index. Two people can genuinely
  // resolve to the same address (a shared alias, or the same person listed at
  // two companies); writing it would abort the whole run on a constraint error,
  // so a NOTE is recorded and the column is left alone. Deliberately not an
  // 'email' observation: under trust-ranked resolution a verifier-source email
  // row would beat the observed one and flip the resolved value to an address
  // that belongs to someone else.
  const owner = get<{ id: string }>(db, 'SELECT id FROM contact WHERE email = ?', email);
  if (owner && owner.id !== contact.id) {
    recordObservation(db, {
      entity: 'contact',
      entityId: contact.id,
      field: 'email_conflict',
      value: `${email} already belongs to another contact`,
      source: pattern ? 'pattern_inference' : 'verifier',
      evidenceId: result.evidenceId,
      confidence: 'low',
    });
    return;
  }

  // The paid verification awaited the network with a PRE-await snapshot of
  // this row. If the operator corrected the address meanwhile, writing the
  // old address (and its verdict) back would erase their edit with stale data.
  const current = get<{ email: string | null }>(db, 'SELECT email FROM contact WHERE id = ?', contact.id);
  if (current && current.email !== contact.email && current.email !== email) {
    recordObservation(db, {
      entity: 'contact',
      entityId: contact.id,
      field: 'email_conflict',
      value: `verification of ${email} finished after the address was changed to ${current.email ?? '(cleared)'} — result not applied`,
      source: 'verifier',
      evidenceId: result.evidenceId,
      confidence: 'low',
    });
    return;
  }

  run(
    db,
    `UPDATE contact SET
       email = ?, email_verdict = ?, email_verified_at = ?, email_source = ?,
       email_pattern = ?, updated_at = unixepoch('subsec')*1000
     WHERE id = ?`,
    email,
    result.verdict,
    result.verifiedAt,
    pattern ? 'pattern_inference' : (contact.email_source ?? 'careers_page'),
    pattern,
    contact.id,
  );

  if (pattern && contact.email !== email) {
    recordObservation(db, {
      entity: 'contact',
      entityId: contact.id,
      field: 'email',
      value: email,
      source: 'pattern_inference',
      evidenceId: result.evidenceId,
      // A guess is low-confidence until a verifier confirms it, at which point
      // the verdict observation below carries the real weight.
      confidence: result.verdict === 'valid' ? 'medium' : 'low',
    });
  }

  recordObservation(db, {
    entity: 'contact',
    entityId: contact.id,
    field: 'email_verdict',
    value: result.verdict,
    source: 'verifier',
    evidenceId: result.evidenceId,
    confidence: result.verdict === 'valid' || result.verdict === 'invalid' ? 'high' : 'medium',
  });
}

/**
 * Run the cascade for one company: free prefilter, pattern conformance, then a
 * single batched paid call for whatever survives.
 */
export async function verifyCompanyContacts(
  db: Db,
  companyId: string,
  opts: VerifyCompanyOptions = {},
): Promise<VerifyCompanyReport> {
  const company = loadCompany(db, companyId);
  if (!company) throw new Error(`Unknown company: ${companyId}`);

  const notes: string[] = [];
  const decisions: VerifyCompanyReport['decisions'] = [];
  const config = opts.config ?? (await loadVerifierConfig(db));

  const suppression = isSuppressed(db, company);
  if (suppression) {
    notes.push(`Skipped — ${suppression}.`);
    return {
      companyId,
      contacts: contactRows(db, companyId).map(toContactRow),
      verified: 0,
      costMicros: 0,
      decisions,
      blocked: false,
      notes,
    };
  }

  const stored = company.domain ? loadPattern(db, company.domain) : null;
  const domainPattern = stored?.pattern ?? null;
  const patternConfidence = stored?.confidence ?? 0;
  const order = company.domain ? globalPatternOrder(db) : [];

  const freshnessMs = config.freshnessDays * 86_400_000;
  const rows = contactRows(db, companyId);

  // Build the work list: one owning contact per address.
  interface Job {
    contact: ContactDbRow;
    email: string;
    pattern: EmailPattern | null;
    rank: number;
  }
  const jobs: Job[] = [];

  for (const c of rows) {
    if (opts.onlyContactId && c.id !== opts.onlyContactId) continue;
    if (c.status === 'contacted' || c.status === 'replied') continue;

    if (c.email) {
      const email = normalizeEmail(c.email);
      if (!email) continue;
      if (emailSuppressed(db, email)) {
        run(db, `UPDATE contact SET status = 'rejected', updated_at = unixepoch('subsec')*1000 WHERE id = ?`, c.id);
        decisions.push({ contactId: c.id, email, decision: 'reject', reason: 'Address is on the suppression list' });
        continue;
      }
      const fresh =
        !opts.force &&
        c.email_verified_at != null &&
        Date.now() - c.email_verified_at < freshnessMs &&
        c.email_verdict !== 'unverified';
      if (fresh) continue;
      jobs.push({ contact: c, email, pattern: (c.email_pattern as EmailPattern) || null, rank: 0 });
      continue;
    }

    if (opts.tryCandidates === false || !company.domain || !c.first_name) continue;
    const limit = domainPattern ? (opts.candidatesWithPattern ?? 1) : (opts.candidatesWithoutPattern ?? 2);
    const candidates = generateCandidates(c.first_name, c.last_name, company.domain, domainPattern, {
      limit,
      confidence: patternConfidence,
      order,
    });
    for (const cand of candidates) {
      if (emailSuppressed(db, cand.email)) continue;
      jobs.push({ contact: c, email: cand.email, pattern: cand.pattern, rank: cand.rank });
    }
  }

  if (jobs.length === 0) {
    return {
      companyId,
      contacts: contactRows(db, companyId).map(toContactRow),
      verified: 0,
      costMicros: 0,
      decisions,
      blocked: false,
      notes: notes.length ? notes : ['Nothing to verify.'],
    };
  }

  const results = await verifyEmails(
    db,
    jobs.map((j) => j.email),
    {
      entityType: 'company',
      entityId: companyId,
      force: opts.force,
      // generateCandidates() never emits a role address, so any role address in
      // this list arrived from a real source and is worth confirming.
      observed: true,
      config,
    },
  );
  const byEmail = new Map(results.map((r) => [r.email, r]));
  const blocked = results.some((r) => r.blocked);
  const costMicros = results.reduce((s, r) => s + r.costMicros, 0);

  // Per contact, take the best answer among its candidates. Ranking mirrors the
  // decision table: a confirmed address beats a catch-all beats an unknown.
  const VERDICT_RANK: Record<VerificationVerdict, number> = {
    valid: 6,
    catch_all: 5,
    unknown: 4,
    role: 3,
    unverified: 2,
    invalid: 1,
    disposable: 0,
  };

  const perContact = new Map<string, Job[]>();
  for (const j of jobs) {
    const list = perContact.get(j.contact.id) ?? [];
    list.push(j);
    perContact.set(j.contact.id, list);
  }

  let verified = 0;
  for (const [contactId, list] of perContact) {
    const contact = list[0]!.contact;
    const scored = list
      .map((j) => ({ job: j, result: byEmail.get(j.email) }))
      .filter((x): x is { job: Job; result: VerifyResult } => Boolean(x.result))
      // A procedural 'unknown' — provider blocked mid-run, or a ledger
      // collision with no evidence behind it — is not a judgement about the
      // address. Applying it would stamp email_verified_at and freeze the
      // contact out of verification for a whole freshness window, and can
      // overwrite a real 'valid' with noise. Drop those results; the contact
      // simply stays as it was and the next run retries.
      .filter((x) => !(x.result.blocked || (x.result.verdict === 'unknown' && x.result.evidenceId == null)))
      .sort(
        (a, b) =>
          VERDICT_RANK[b.result.verdict] - VERDICT_RANK[a.result.verdict] || a.job.rank - b.job.rank,
      );
    if (scored.length === 0) continue;

    const best = scored[0]!;
    const looksDead = VERDICT_RANK[best.result.verdict] <= VERDICT_RANK.invalid;

    // A guessed address that came back dead must not be written onto the
    // contact — the person is real, the guess was wrong.
    if (best.job.pattern && !contact.email && looksDead) {
      run(
        db,
        `UPDATE contact SET email_verdict = 'unverified', email_verified_at = ?, updated_at = unixepoch('subsec')*1000
          WHERE id = ?`,
        best.result.verifiedAt,
        contactId,
      );
      decisions.push({
        contactId,
        email: null,
        decision: 'reject',
        reason: `No working address found (${scored.length} candidate${scored.length === 1 ? '' : 's'} tried)`,
      });
      continue;
    }

    applyVerdict(db, contact, best.job.email, best.result, best.job.pattern);
    verified++;

    const conformance = patternConformance(
      best.job.email,
      contact.first_name,
      contact.last_name,
      domainPattern,
      patternConfidence,
    );
    const sourceCount = sourceCountFor(db, contactId, best.job.email);
    const decision = decideContact({
      verdict: best.result.verdict,
      // The provider's answer wins; when it said nothing about catch-all, the
      // per-domain flag saved from earlier verifications fills the gap.
      catchAll: best.result.catchAll ?? getCatchAllFlag(db, domainOf(best.job.email)),
      patternConformance: conformance,
      sourceCount,
      role: best.result.role || isRoleAccount(best.job.email),
      mxReliability: best.result.mxProvider ? verdictReliability(best.result.mxProvider) : undefined,
    });
    decisions.push({ contactId, email: best.job.email, decision: decision.decision, reason: decision.reason });

    // Only rejection is automatic. Everything else stays a candidate for the
    // operator, who reviews every record by design.
    if (decision.decision === 'reject' && contact.status === 'candidate') {
      run(db, `UPDATE contact SET status = 'rejected', updated_at = unixepoch('subsec')*1000 WHERE id = ?`, contactId);
    }
    recordObservation(db, {
      entity: 'contact',
      entityId: contactId,
      field: 'outreach_decision',
      value: `${decision.decision}: ${decision.reason}`,
      source: 'verifier',
      evidenceId: best.result.evidenceId,
      confidence: 'high',
    });
  }

  // A newly confirmed address is a new seed, so the domain's pattern is
  // re-derived from real observations rather than from its own guesses.
  if (company.domain) {
    const refreshed = refreshPattern(db, company.domain);
    if (refreshed.pattern) {
      notes.push(
        `Pattern ${refreshed.pattern} at ${refreshed.confidence.toFixed(2)} confidence from ${refreshed.sampleCount} observed address${refreshed.sampleCount === 1 ? '' : 'es'}.`,
      );
    }
  }

  rescoreCompanyContacts(db, companyId, company);

  if (blocked) notes.push('Verification provider returned 429/403 — this source has been stopped.');
  if (costMicros > 0) notes.push(`Spent $${(costMicros / 1e6).toFixed(4)}.`);

  return {
    companyId,
    contacts: contactRows(db, companyId).map(toContactRow),
    verified,
    costMicros,
    decisions,
    blocked,
    notes,
  };
}

/** Recompute contact_score for every contact at a company and mark the primary. */
export function rescoreCompanyContacts(db: Db, companyId: string, preloaded?: Company | null): void {
  const company = preloaded ?? loadCompany(db, companyId);
  if (!company) return;
  const rows = contactRows(db, companyId);
  if (rows.length === 0) return;

  for (const r of rows) {
    const score = scoreContact(toContact(r), company);
    run(
      db,
      'UPDATE contact SET contact_score = ?, updated_at = unixepoch(\'subsec\')*1000 WHERE id = ?',
      score,
      r.id,
    );
  }

  // One elector for the whole app. This function used to run its own (score
  // only), which ignored both the reviewed-manual-primary rule and the
  // prefer-contacts-with-an-address rule — whichever path wrote last won.
  electPrimaryContact(db, companyId);
}

/** Single-contact re-verification, for the operator's `v` key. */
export async function verifyContactById(
  db: Db,
  contactId: string,
  opts: { force?: boolean } = {},
): Promise<ContactRow | null> {
  const contact = get<ContactDbRow>(db, 'SELECT * FROM contact WHERE id = ?', contactId);
  if (!contact) return null;
  await verifyCompanyContacts(db, contact.company_id, {
    force: opts.force ?? true,
    tryCandidates: true,
    onlyContactId: contactId,
  });
  const after = get<ContactDbRow>(db, 'SELECT * FROM contact WHERE id = ?', contactId);
  return after ? toContactRow(after) : null;
}

/**
 * How many paid credits a run over these companies would need, so the Pipeline
 * screen can show a cost before the operator confirms.
 */
export function estimatePendingVerifications(db: Db, freshnessDays: number): number {
  const cutoff = Date.now() - freshnessDays * 86_400_000;
  const withEmail =
    get<{ n: number }>(
      db,
      `SELECT count(*) AS n FROM contact
        WHERE email IS NOT NULL
          AND status NOT IN ('rejected','contacted','replied','bounced')
          AND (email_verified_at IS NULL OR email_verified_at < ?)`,
      cutoff,
    )?.n ?? 0;
  const withoutEmail =
    get<{ n: number }>(
      db,
      `SELECT count(*) AS n FROM contact c
        JOIN company co ON co.id = c.company_id
       WHERE c.email IS NULL AND c.first_name IS NOT NULL AND co.domain IS NOT NULL
         AND c.status NOT IN ('rejected','contacted','replied','bounced')`,
    )?.n ?? 0;
  // People with no address get more than one candidate tried.
  return withEmail + withoutEmail * 2;
}
